### PR TITLE
Ubuntu1604

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@cliff-wakefield Could you give this branch a try?

**Comment by cliff-wakefield** [comment]
Makes for some messy config files vs the default ones.

ssh_config diff https://gist.github.com/cliff-wakefield/ed6c4868c4e40a6167f2fc39b8eb6a1e
sshd_config diff https://gist.github.com/cliff-wakefield/d65c3405634d1e1014fa698f4d316e7e

hiera settings
global.yaml https://gist.github.com/cliff-wakefield/3740fec3343b294922324d85dd2a6f35

**Comment by ghoneycutt** [comment]
@Phil-Friderici I'm at a loss here, you have any ideas regarding the spec tests?

**Comment by Phil-Friderici** [comment]
@ghoneycutt please check https://github.com/ghoneycutt/puppet-module-ssh/pull/189

**Comment by ghoneycutt** [comment]
Released in v3.45.0

**Comment by Phil-Friderici** [comment]
@cliff-wakefield Thanks for your work adding support for Ubuntu 16.06 !

**Pull request merged**
