### PR TITLE
Disable ServerkeyBits on RHEL 7.4 and later

### LINKED ISSUE #244: ServerKeyBits Deprecated in RHEL 7.4
As of RHEL 7.4 ServerKeyBits is now a deprecated option.

Warning Message in /var/log/messages:
Deprecated option ServerKeyBits

### PR DESCRIPTION
**Pull request by tuxmea**
fixes #244
replaces #259

### CODE REVIEW

**Comment by tuxmea** [comment]
@ghoneycutt I need your help on tests with Puppet 4 and 5.
Why do tests fail with missing facter variable $::operatingsystemrelease?

**Comment by tuxmea** [comment]
Can someone retigger the build? Failure seems not coming from Puppet code.

**Comment by ghoneycutt** [comment]
retriggered the failing job

**Comment by ghoneycutt** [comment]
@tuxmea Could you please rebase and squash and I'll get this merged. Thanks for the contribution!

**Comment by tuxmea** [comment]
@ghoneycutt rebased and squashed

**Comment by ghoneycutt** [comment]
Released in v3.57.1

**Pull request merged**
