### PR TITLE
Ubuntu1604

### PR DESCRIPTION
**Pull request by Phil-Friderici**
Let's try my fix that was needed on the yum module.

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
Puppet 4.0 -> 4.2 fix: Hiera usage now demands having the used facts available.
Puppet 4.6 fix: adjust gem pinning

With that it works again :)

**Comment by ghoneycutt** [comment]
Wow! Thanks

**Comment by ghoneycutt** [comment]
Released in v3.45.0

**Comment by cliff-wakefield** [comment]
Changelog not updated by the way ;)

**Comment by cliff-wakefield** [comment]
Will test 3.45.0 very soon.

**Comment by ghoneycutt** [comment]
Thanks for the reminder! I updated the CHANGELOG.

**Pull request merged**
