### PR TITLE
Adding two new options for sshd_config PermitEmptyPasswords and PermitUserEnvironment

### PR DESCRIPTION
**Pull request by jthiesfeld**

### CODE REVIEW

**Comment by jthiesfeld** [comment]
I think I created a giant mess by merging one of your changes into the middle of my branch on my previous attempt.

Do you have information on how I can test my module before pushing into github?  That should help me with creating a giant mess of commits.

Thanks for your patience.

**Comment by ghoneycutt** [comment]
you can test by running the same commands that Travis-ci does

https://github.com/ghoneycutt/puppet-module-ssh/blob/master/.travis.yml#L30

before running that, run `bundle install`

**Comment by ghoneycutt** [comment]
To improve your git skills check out

https://github.com/unixmonkey/learngit

and

https://github.com/Gazler/githug

**Comment by jthiesfeld** [comment]
Anything I need to adjust in this version before it can be merged?

**Comment by ghoneycutt** [comment]
Thanks!
Released in v3.42.0

**Pull request merged**
