### PR TITLE
Add configurable param X11UseLocalhost to sshd_config

### PR DESCRIPTION
**Pull request by boandersson**
Setting requested by LSF users for submitting X-based jobs via LSF.

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@boandersson Thank you!

Please document the new parameter in the README.md  and this should be good to merge.

Have you had a chance to functionally test this on your systems?

**Comment by boandersson** [comment]
Thanks @ghoneycutt,
Sorry - always seem to forget something... I've updated the README now.
We run this commit in production now without issues.

**Comment by ghoneycutt** [comment]
Thank you!

**Comment by ghoneycutt** [comment]
Released in v3.46.0

**Pull request merged**
