### PR TITLE
V4 again take 2

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
I am very happy to see progress with v4, but it feels a bit sad that all the work I had put in it is now lost because of the rebase.

**Comment by treydock** [comment]
@Phil-Friderici I modified the commit to make you author and added myself as co-author.

**Comment by canihavethisone** [comment]
Why is puppet version restricted to 7 in this pr? Is it no longer compatible with v6?

**Comment by treydock** [comment]
I can't speak to why this was restricted to Puppet 7 as I just took over the v4 refactoring and only added RHEL8 bits.  Generally speaking if a module supports Puppet 7, it will also work with Puppet 6 as there were not significant changes between those Puppet versions that would cause modules to break.  In the context of this module, it's just about what is tested against.

**Comment by canihavethisone** [comment]
@treydock @ghoneycutt I'm concerned about the **minimum** stdlib version being 8. Is this absolutely required? Also if its compatible with puppet 6 it would be good to have that in the metadata

**Comment by ghoneycutt** [comment]
@canihavethisone Puppet 6 is deprecated and we are not spending any effort to support it. As Trey mentioned, it will likely "just work" though you may have to adjust your module management processes to allow for it and your other older dependencies such as stdlib.

**Comment by canihavethisone** [comment]
@ghoneycutt according to https://puppet.com/docs/puppet/6/platform_lifecycle.html puppet 6 is in support until July 2023.

The bigger concern to me is having the lowest version of stdlib at v8.  If this is not required for new functions, can you please consider lowering it to v6 to ensure backwards compatibility?

**Pull request merged**
