### PR TITLE
Setting mode of sshd_config file for Suse to vendor default.

### PR DESCRIPTION
**Pull request by ejabach**
As requested by @Phil-Friderici
Any concerns?

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
@ejabach thanks for taking care.
@ghoneycutt this patch will set the file mode back to the OS vendor default.
Some of Susies tools will reset the file mode back to 0640. Running into a changed state with the next Puppet run.

**Comment by ghoneycutt** [comment]
I believe the default is supposed to be 0600.

**Comment by Phil-Friderici** [comment]
Suse decided to change it's vendor default to 0640. If you think the module should roll out the vendor default, please merge it. If you think it should roll out the SSH close it please ;)

**Comment by ghoneycutt** [comment]
I think it should default to the less permissive mode of 0600. Curious, which of Suse's tools are messing with that? You can work around this with Hiera for your Suse systems, which I'm guessing you're already doing..

**Comment by Phil-Friderici** [comment]
@ghoneycutt yeah sure, we are overriding it via hiera these days.

**Pull request closed without merging**
