### PR TITLE
Minor change rollup (fixes #276)

### LINKED ISSUE #276: add id_ed25519 support
Given: OpenSSH_7.4p1, OpenSSL 1.0.2k-fips on Centos 7 and Puppet 5 and the manifest ```include ssh```
When I: try to use a pre-existing ssh ed25529 key to ssh into another server.
I get: a password prompt.
I expected: to log straight in with the private key.

Investigation shows that this module has wiped out the ssh_config entries as follows:
```
-   IdentityFile ~/.ssh/id_ecdsa
-   IdentityFile ~/.ssh/id_ed25519
```
and the sshd_config entries as follows:
```
-HostKey /etc/ssh/ssh_host_ecdsa_key
-HostKey /etc/ssh/ssh_host_ed25519_key
```
This is a nuisance because we've adopted ed25519 widely already.

Double-checking this morning, SSH with the -v option gave:
```
debug1: permanently_set_uid: 0/0
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
```
so ssh is definitely no longer even trying to load the id_ed25519 key.

### PR DESCRIPTION
**Pull request by threepistons**
# Add Identifyfile management
This defaults to putting in id_rsa and id_dsa default identity files as it did before, so it shouldn't break existing installations of this module.  Suggestion for next release: add sensible defaults for newer OSes.  I added tests for this in the big spec file.

Apply with Hiera
```
ssh::ssh_config_identityfiles:
  - ~/.ssh/id_ed25519
  - ~/.ssh/id_rsa
  - ~/.ssh/id_ecdsa
```
or Puppet
```
class ssh {
  ssh_config_identityfiles => [ '~/.ssh/id_ed25519',
    '~/.ssh/id_rsa',
    '~/.ssh/id_ecdsa'
  ]
}
```
# Update to support ed25519
There's a host key validator that didn't have a case for ed25519.  It now does.  No spec test (there wasn't for the rest of the case block) but it has been tested on a vm and works.  Non-breaking change.

# Add support for prohibit-password
```PermitRootLogin prohibit-password``` is now permitted by the validator.  No spec test, there wasn't one for the existing validator.  Works on a vm.    Non-breaking change.

# test with RHEL7
I've updated the spec defaults to use Redhat 7 and its shipped OpenSSH.  Tests all still worked on prior code. 

# Documentation
The readme file now has the *ssh_config_identityfiles* parameter documented with an example.

### CODE REVIEW

**Comment by threepistons** [comment]
I'm really puzzled: the Travis build passed for #4a6f6cb and has failed since, even when I've reverted my changes.  @ghoneycutt, have you changed your Travis settings?

**Comment by ghoneycutt** [comment]
Thank you for your contributions! Please group pull requests by individual functionality or bug fix. When you send multiple things together, it becomes hard to merge them. When sending discrete pull requests it makes it much easier to get things merged.

**Comment by threepistons** [comment]
Splitting these up is in my job queue.  Thanks for the pointer, I'm new to this.

**Comment by threepistons** [comment]
I'm breaking out and resubmitting all my changes bar the RHEL7 test support, as I see something that looks like RHEL7 tests in your later commits.

**Pull request closed without merging**
