### PR TITLE
Add possibility to add extra config lines

### PR DESCRIPTION
**Pull request by scoopex**
Simple addition to have extra config lines.

### CODE REVIEW

**Comment by scoopex** [comment]
Synced with upstream.

**Comment by scoopex** [comment]
Strange, running the tests locally succeeds without problems:
```
PUPPET_GEM_VERSION="~> 6" SPEC_OPTS="--format documentation" bundle exec rake validate lint spec
....


1 deprecation warning total

Finished in 42.12 seconds (files took 0.92174 seconds to load)
903 examples, 0 failures
```

**Comment by scoopex** [comment]
I also get these error messages if i execute the tests on git@github.com:ghoneycutt/puppet-module-ssh.git 
Not seems to be related to my changes.

**Comment by Phil-Friderici** [comment]
Closing this PR as it was made for the v3 version of the module which is outdated now.
v4 does allow to set additional lines in ssh(d)_config with the `$ssh::custom` and `$ssh::server::custom` parameters.

**Pull request closed without merging**
