### PR TITLE
Add support for Debian 12 and Ubuntu 24.04

### PR DESCRIPTION
**Pull request by flichtenheld**
Simple copy of Debian 11 and Ubuntu 22.04 config. Saw no reason to change any of the defaults. Definitely better than the global defaults...

Fixes: #427

### CODE REVIEW

**Comment by ghoneycutt** [comment]
This data is valid, so people can copy it and use it today before it is merged as this module is forward compatible in that way.

**Comment by ghoneycutt** [comment]
@flichtenheld could you please add the acceptance testing to support this?

**Comment by flichtenheld** [comment]
Will do

**Comment by flichtenheld** [comment]
> @flichtenheld could you please add the acceptance testing to support this?

@ghoneycutt  Added enough to make `pdk test unit` pass. Let me know if there is anything else I should run.

**Comment by flichtenheld** [comment]
Now also enabled GHA tests and rebased on newest main.

**Comment by ghoneycutt** [comment]
Approved the tests and they are coming up with errors.

**Comment by ghoneycutt** [comment]
Thanks @baurmatt and @flichtenheld !

**Pull request merged**
