### PR TITLE
Update concat dependency to be compatible with concat 3.x and 4.x

### PR DESCRIPTION
**Pull request by dhollinger**
addresses #247

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@dhollinger Which concat version are you using? Could you exercise the new ssh::config_entry defined type as shown in the example and validate that it works?

https://github.com/ghoneycutt/puppet-module-ssh#sample-usage

**Comment by dhollinger** [comment]
@ghoneycutt I can test it. We are on the latest `puppetlabs-concat`, which I believe is `4.0.1`

**Comment by ghoneycutt** [comment]
If you could please manually test it. I'll wait to update the `.fixtures.yml` for the next version when the code drops support for Puppet 3.

**Comment by dhollinger** [comment]
Sorry for the delay in updating.

Ran manual tests and they succeeded:

Code:
```puppet
class profile::puppet::master {
  include '::pmaster_profile'

  ssh::config_entry { 'root *':
    ensure => present,
    path   => '/root/config',
    owner  => 'root',
    group  => 'root',
    host   => '*',
    lines  => [
      '  ForwardX11 no',
      '  StrictHostKeyChecking no',
    ],
    order => '10',
  }
}
```

Agent log:
```
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for dev-fusion-puppetserver.fuslab.net
Info: Applying configuration version '1509117861'
Notice: /Stage[main]/Profile::Puppet::Master/Ssh::Config_entry[root *]/Concat[/root/config]/File[/root/config]/ensure: defined content as '{md5}e67bcac2b30db2852663c3f503a2a6f2'
Notice: Applied catalog in 7.88 seconds
```

File Contents:
```
Host *
  ForwardX11 no
  StrictHostKeyChecking no
```

Tested with `puppetlabs-concat 4.0.1`

**Comment by ghoneycutt** [comment]
Fixes #247

**Comment by ghoneycutt** [comment]
Released in v3.56.0

**Pull request merged**
