### PR TITLE
Add support for KexAlgorithms parameter to avoid logjam vulnerability

### PR DESCRIPTION
**Pull request by greigm**
See https://stribika.github.io/2015/01/04/secure-secure-shell.html for details.
Absent by default.

### CODE REVIEW

**Comment by kindred** [comment]
Any idea when this will be merged in?

**Comment by reuterbal** [comment]
Can this be merged, please?

**Comment by ghoneycutt** [comment]
Thank you for the contribution! Additional parameters must be documented in the README and be fully tested with spec tests. This is missing the documentation and some of the spec tests.

**Comment by greigm** [comment]
Hrm, I'll get to that eventually. I no longer work for the organisation which motivated these changes so no longer care so much. ;) Should anyone else wish to add the docs/spec tests, you're most welcome!

**Comment by ghoneycutt** [comment]
I understand :)

Thank you!

**Comment by Asteao** [comment]
This functionality has been implemented with #195

**Comment by Phil-Friderici** [comment]
Closing this PR as it was made for the v3 version of the module which is outdated now.
v4 does allow to set `KexAlgorithms` in sshd_config with the `$ssh::server::kex_algorithms` parameter.

**Pull request closed without merging**
