### PR TITLE
add default SFTP subsystem for SLES12

### PR DESCRIPTION
**Pull request by Phil-Friderici**
On SLES 12 the SFTP subsystem changed the path.

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Looks good. Could you please add SLES12 support to the README and metadata.json?

**Comment by Phil-Friderici** [comment]
schwupps

**Comment by ghoneycutt** [comment]
Released in v3.31.0

Thank you!

**Comment by Phil-Friderici** [comment]
Thanks a lot too :)

**Pull request merged**
