### PR TITLE
move empty line into conditional block

### PR DESCRIPTION
**Pull request by Phil-Friderici**
no nothing, just beautifying the output file

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Is this because of the last PR that effectively added a newline for everyone if their config didn't change?

**Comment by Phil-Friderici** [comment]
yes :(

**Comment by ghoneycutt** [comment]
Eh, no worries. Since this is only a whitespace change, I'm not going to bother with a release and will release it with the next PR. That is, unless you especially want this tagged.

**Comment by Phil-Friderici** [comment]
No need for a new release, it's just a cosmetical issue.

**Pull request merged**
