### PR TITLE
validate_cmd support

### PR DESCRIPTION
**Pull request by Raskil**
added support to validate sshd_config before putting a new config file
in place.

### CODE REVIEW

**Comment by lazyfrosch** [comment]
Wow this change is pretty heavy, a lot of indention and white space changes.

You should reduce that to an absolute minimum, and only include the actual changes. Be careful with IDEs

**Comment by lazyfrosch** [comment]
@Raskil a note, you can leave that PR open, correct your changes, and force push to the same branch. This will update your PR.

**Comment by Raskil** [comment]
Thanks for the note, I'll try that the next time.

**Comment by ghoneycutt** [comment]
This is in PR #124

**Pull request closed without merging**
