### PR TITLE
Added AddressFamily option in sshd_config.

### PR DESCRIPTION
**Pull request by bschonec**
Currently, it's hard coded to "any".  This allows any, inet or inet6.

I've been watching and reading about how to make spec files but I'm no developer by any means.  Therefore, I've not included any changes to the spec files.

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
oh, this is mostly a duplicate to https://github.com/ghoneycutt/puppet-module-ssh/pull/131

**Comment by bschonec** [comment]
So is this not needed then?  I've updated the README.md but due to my utter lack of how GIT works it seems I've 'merged' other changes that I've made.

**Comment by ghoneycutt** [comment]
@bschonec Thanks for the contribution though we are going with PR #131 as it already has tests and is one simple change away from being acceptable.

**Comment by Phil-Friderici** [comment]
@bschonec Thanks for your work! Guess the merged change also fit your needs.

**Pull request closed without merging**
