### PR TITLE
Support for Debian 11 (bullseye)

### LINKED ISSUE #361: Support for Debian 11
Copying the config for Debian 10 and changing to to 11 seems to work just fine for now, but wanted to request Debian 11 support get added.

Thanks

### PR DESCRIPTION
**Pull request by vilhelmprytz**
Fixes #361 

This is pretty much a duplicate of #355 but more complete. I have tested it to work on Debian 11!

### CODE REVIEW

**Comment by vilhelmprytz** [comment]
@ghoneycutt I basically installed default Debian 11 (`debian-11.1.0-amd64-netinst.iso`) and copied the contents of `/etc/ssh_config` and `/etc/sshd_config` to this repo. I then added the following to the top.

```
# This file is being maintained by Puppet.
# DO NOT EDIT
```

Is this better?

**Comment by ghoneycutt** [comment]
Yes, perfect!

Please update the `metadata.json` and this should be ready.

**Comment by vilhelmprytz** [comment]
@ghoneycutt Done!

**Comment by ghoneycutt** [comment]
This is failing the spec tests

**Comment by vilhelmprytz** [comment]
I've quickly read through the failing CI tests. I'm not too familiar with Ruby and Puppet modules, what is it that I need to change?

```
is expected to contain File[sshd_config] with content  supplied string (FAILED - 2)
```

Do I understand it correctly that it checks for specific strings in some files? What strings is it checking for and why?

**Comment by vilhelmprytz** [comment]
These CI jobs are to me quite unreadable, over 8000 lines on just one of them! https://app.travis-ci.com/github/vilhelmprytz/puppet-module-ssh/jobs/546119676

It seems like it complains about missing the following.

```
$OpenBSD: ssh_config,v 1.21 2005/12/06 22:38:27 reyk Exp $
```

This was not included in `/etc/ssh/ssh_config` on Debian 11 by default.

And if I understand it correctly that this diff is what the CI job expects, then the file will end up being pretty much the same as for Debian 10? https://app.travis-ci.com/github/vilhelmprytz/puppet-module-ssh/jobs/546119676#L4522

**Comment by vilhelmprytz** [comment]
Anything new regarding this? I would be happy to modify my PR to suit the tests, but I think it will end up looking like the config files for Debian 10 and then I don't understand why there are different configs for the different releases.

**Comment by vilhelmprytz** [comment]
Hello again, do you have any updates regarding this? I would happily modify the PR to suit the needs of the project 🙂

**Comment by vilhelmprytz** [comment]
@ghoneycutt Anything new regarding this?

**Comment by ghoneycutt** [comment]
@Phil-Friderici is working on big changes for this code so not merging anything until he is done. The data from this will be very helpful to get this platform supported. Thanks!

**Comment by Phil-Friderici** [comment]
Hej @vilhelmprytz, I have adapted your work into a [commit ](https://github.com/ghoneycutt/puppet-module-ssh/pull/373/commits/aa74414c1a6398fad6a3896783d69d465c06e892) that will get merged into the v4 branch and eventually become part of the main branch.

Thank you for your good work !!

**Comment by Phil-Friderici** [comment]
Sorry, needed to rebase this commit. It moved to [here](https://github.com/ghoneycutt/puppet-module-ssh/pull/373/commits/3a350b3ad5228f6a1deb690a2c20cf850aa8a412).

**Comment by vilhelmprytz** [comment]
What's the status of this?

**Comment by Phil-Friderici** [comment]
It got merged into the v4 branch which is waiting to become merged into the master branch.

**Comment by mlausch** [comment]
Hi, I want to use this module with Debian 11. When do you think, this will be merged and released?

**Comment by Phil-Friderici** [comment]
Closing this PR that was made for the (now outdated) v3 version of the module.
I have integrated support for Debian 11 in my PR https://github.com/ghoneycutt/puppet-module-ssh/pull/398.

**Pull request closed without merging**
